### ISSUE TITLE
StatefulSet in K8s

### ISSUE THREAD

**Issue by SarthakSingh18** [scorelab/Scan8#8]
I will be writing a blog about StatefulSet in K8s.

**Comment by SarthakSingh18** [comment]
This is my draft link for the blog regarding Stateful Components @kmehant 
https://medium.com/@sarthaksingh0900/statefulset-in-k8s-24a0b3a30ec9

**Comment by kmehant** [comment]
@SarthakSingh18 This task expects some learnings for Handling Secrets, env variables, and as you mentioned various components of K8s as its title. I think the present doc is good enough for a stateful set. 

Can you change the issue title and also create more issues on the remaining parts separately (secrets, env, and other components of K8s). 

I request one more review from @Ammoniya @1209973 so that we can close this issue!

**Comment by SarthakSingh18** [comment]
Done @kmehant
